//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPClient.CFService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.dotnethell.it/CodiceFiscale", ConfigurationName="CFService.CodiceFiscaleSoap")]
    public interface CodiceFiscaleSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.dotnethell.it/CodiceFiscale/CalcolaCodiceFiscale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CalcolaCodiceFiscale(string Nome, string Cognome, string ComuneNascita, string DataNascita, string Sesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.dotnethell.it/CodiceFiscale/CalcolaCodiceFiscale", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CalcolaCodiceFiscaleAsync(string Nome, string Cognome, string ComuneNascita, string DataNascita, string Sesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.dotnethell.it/CodiceFiscale/CodiceComune", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CodiceComune(string NomeComune);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.dotnethell.it/CodiceFiscale/CodiceComune", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CodiceComuneAsync(string NomeComune);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.dotnethell.it/CodiceFiscale/NomeComune", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string NomeComune(string CodiceComune);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.dotnethell.it/CodiceFiscale/NomeComune", ReplyAction="*")]
        System.Threading.Tasks.Task<string> NomeComuneAsync(string CodiceComune);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.dotnethell.it/CodiceFiscale/ControllaCodiceFiscale", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ControllaCodiceFiscale(string CodiceFiscale);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.dotnethell.it/CodiceFiscale/ControllaCodiceFiscale", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ControllaCodiceFiscaleAsync(string CodiceFiscale);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CodiceFiscaleSoapChannel : SOAPClient.CFService.CodiceFiscaleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CodiceFiscaleSoapClient : System.ServiceModel.ClientBase<SOAPClient.CFService.CodiceFiscaleSoap>, SOAPClient.CFService.CodiceFiscaleSoap {
        
        public CodiceFiscaleSoapClient() {
        }
        
        public CodiceFiscaleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CodiceFiscaleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodiceFiscaleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CodiceFiscaleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CalcolaCodiceFiscale(string Nome, string Cognome, string ComuneNascita, string DataNascita, string Sesso) {
            return base.Channel.CalcolaCodiceFiscale(Nome, Cognome, ComuneNascita, DataNascita, Sesso);
        }
        
        public System.Threading.Tasks.Task<string> CalcolaCodiceFiscaleAsync(string Nome, string Cognome, string ComuneNascita, string DataNascita, string Sesso) {
            return base.Channel.CalcolaCodiceFiscaleAsync(Nome, Cognome, ComuneNascita, DataNascita, Sesso);
        }
        
        public string CodiceComune(string NomeComune) {
            return base.Channel.CodiceComune(NomeComune);
        }
        
        public System.Threading.Tasks.Task<string> CodiceComuneAsync(string NomeComune) {
            return base.Channel.CodiceComuneAsync(NomeComune);
        }
        
        public string NomeComune(string CodiceComune) {
            return base.Channel.NomeComune(CodiceComune);
        }
        
        public System.Threading.Tasks.Task<string> NomeComuneAsync(string CodiceComune) {
            return base.Channel.NomeComuneAsync(CodiceComune);
        }
        
        public string ControllaCodiceFiscale(string CodiceFiscale) {
            return base.Channel.ControllaCodiceFiscale(CodiceFiscale);
        }
        
        public System.Threading.Tasks.Task<string> ControllaCodiceFiscaleAsync(string CodiceFiscale) {
            return base.Channel.ControllaCodiceFiscaleAsync(CodiceFiscale);
        }
    }
}
